name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Build Node.js'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install client dependencies
      run: npm ci
      working-directory: ./laty-RPG-app/client
    - name: Install server dependencies
      run: npm ci
      working-directory: ./laty-RPG-app/server
    - run: npm run build --if-present
      working-directory: ./laty-RPG-app/server
    - run: npm test
