name: Node.js CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        description: 'Build Node.js'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.16]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install client dependencies
      run: npm ci
      working-directory: ./laty-RPG-app/client
    - name: Install server dependencies
      run: npm ci
      working-directory: ./laty-RPG-app/server
    - run: npm run build --if-present
      working-directory: ./laty-RPG-app/server
    #- run: npm test
    
    - name: Add remote origin
      run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: Deploy backend to heroku
      run: git push --force heroku `git subtree split --prefix server HEAD`:master
